---

dependencies:

  - role: debops.php/env
    tags: [ 'depend::php', 'depend::php:wordpress', 'depend-of::wordpress', 'type::dependency:hard' ]

  - role: debops.php
    tags: [ 'depend::php', 'depend::php:wordpress', 'depend-of::wordpress', 'type::dependency' ]
    php__default_pools: []
    php__packages: '{{ wordpress__php__packages }}'
    php__pools: [ '{{ wordpress__php__pool }}' ]
    php__ini_memory_limit: '{{ wordpress__php__memory_limit }}'
    php__ini_post_max_size: '{{ wordpress__php__post_max_size }}'
    when: ('php' in wordpress__dependencies)
