---

# ---- Install and configure WordPress ----

- name: Create WordPress directory
  file:
    path: '{{ wordpress__root }}'
    state: 'directory'
    owner: '{{ wordpress__user_name }}'
    group: '{{ wordpress__user_group }}'
    mode: '0755'

- name: Check if WordPress is installed
  command: 'wp core is-installed'
  become_user: '{{ wordpress__user_name }}'
  args:
    chdir: '{{ wordpress__root }}'
  register: wordpress__register_installed
  changed_when: False
  failed_when: False

- include: 'install_{{ wordpress__install_type }}.yml'
  when: wordpress__register_installed is defined and wordpress__register_installed.rc == 1

- name: Setup WordPress permalink structure
  command: 'wp rewrite structure {{ wordpress__permalink_structure }}'
  become_user: '{{ wordpress__user_name }}'
  args:
    chdir: '{{ wordpress__root }}'
