---

- name: Manage WordPress web server
  hosts: 'wordpress'
  become: True

  roles:
    - role: debops.swapfile
      tags: [ 'role::swap', 'swap' ]
      swapfile__swappiness: '15'
    - role: debops.postfix
      tags: [ 'role::postfix', 'postfix' ]
    - role: wordpress
      tags: [ 'role::wordpress', 'wordpress' ]
